[deployment]
# Static deployment configuration for TexEcon.com
deploymentTarget = "static"
publicDir = "dist/public"
buildCommand = "vite build"

[workspace]
language = "typescript"
command = "./scripts/static-dev.sh"

[workspace.ports]
5000.description = "Static web server"
5000.openBrowser = true